name = "miniflux-ui"

main = "src/index.ts"

workers_dev = false

preview_urls = true

compatibility_date = "2025-06-27"

[observability]
enabled = true

[placement]
mode = "smart"

[assets]
binding = "ASSETS"
not_found_handling = "404-page"
html_handling = "auto-trailing-slash"