name: Build and Deploy to gh-pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.husky/**'
      - '.editorconfig'
      - '.gitignore'
      - 'biome.json'
      - 'Caddyfile'
      - 'Dockerfile'
      - 'README*.md'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{github.ref}}
    runs-on: ubuntu-latest
    if: github.repository == 'electh/ReactFlux'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install and Build
        run: |
          pnpm install --frozen-lockfile
          pnpm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.6.8
        with:
          branch: gh-pages
          folder: build
