name: Update Docker Hub Description
on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml

  workflow_dispatch:

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    if: github.repository == 'electh/ReactFlux'
    steps:
      - uses: actions/checkout@v4

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: electh/reactflux
          short-description: ${{ github.event.repository.description }}
          enable-url-completion: true
